image: fedora

before_script:
  - dnf update && dnf install -y cmake gcc clang-devel qt5* boost-devel

build:
  script:
    - mkdir build/
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make
