image: fedora

before_script:
  - dnf update -y && dnf install -y cmake gcc clang-devel qt5-qtbase-devel boost-devel

stages:
  - build
  - test

build_spag:
  stage: build
  script:
    - mkdir build/
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make package
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - build/spaghetti-gui-0.2.0-Linux.rpm

run_ut:
  stage: test
  script:
    - cd build
    - ./unittest
