image: nestal/spaghetti-build

before_script:
  - dnf update -y && dnf install -y cmake gcc clang-devel qt5-qtbase-devel boost-devel rpm-build

stages:
  - build
  - test

build_spag:
  stage: build
  script:
    - mkdir build/
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make package
    - ./unittest
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - build/*.rpm
